yaml


name: Aamuinen kyberbotti
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Hae koodi
        uses: actions/checkout@v4
      
      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Asenna riippuvuudet
        run: pip install -r requirements.txt
        
      - name: Aja ohjelma ja lähetä kooste
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python botti.py
